sourceflag:
  agile-logger:
    enable: true
    log-mode: database
    async: true
    async-params:
      core-pool-size: 1
      maximum-pool-size: 2
    database:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root