sourceflag:
  agile-logger:
    enable: true
    uri-prefix:
    log-mode: custom
    async:
      enable: true
      async-params:
        core-pool-size: 1
        maximum-pool-size: 2
    url-filter:
      includes: [".*"]
      excludes: []
    response-success-define:
      code-fields:
        - name: errcode
          value: 0
        - name: code
          value: 200
        - name: code
          value: 100
        - name: result
          value: 00
      message-fields: message, msg
    plugins:
      database:
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
      cache:
        initial-capacity: 200
        maximum-size: 2000
        expired-time: 3600000
      redis:
        database: 1
        host: 127.0.0.1
        port: 6379
        expired-time: 3600000
        username: root
        password: root
        minIdle: 1
        max-idle: 8
        max-active: 8
        max-wait: -1
        key-prefix: agile
    rpc:
      feign:
        enable: true
      rest-template:
        enable: true
    config:
      track:
        use-sky-walking-trace: false
        name: x-track-id
      version:
        name: version
      mock:
        enable: true
        expire-after-write: 600
        expire-after-access: 600
      curl:
        enable: true

domain:
  oms-url: oms
  oc-url: oc
  ic-url: ic